# Samples of ndarray creating

In [1]:
import numpy as np
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}', sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.1


## array

In [2]:
a = np.array(range(5))
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (5,); int64
[0 1 2 3 4]


In [3]:
a = np.array([1, 3, 5, 2])
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (4,); int64
[1 3 5 2]


In [4]:
a = np.array([[1, 3], [5, 2]], dtype=int)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

2; (2, 2); int64
[[1 3]
 [5 2]]


In [5]:
a = np.array([[1, 3], [5, 2], [1, 1]])
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

2; (3, 2); int64
[[1 3]
 [5 2]
 [1 1]]


In [6]:
a = np.array([[1, 3.5], [5, 2]])
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

2; (2, 2); float64
[[1.  3.5]
 [5.  2. ]]


In [7]:
a = np.array([[1, 3.5],[5, 2+1j]])
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

2; (2, 2); complex128
[[1. +0.j 3.5+0.j]
 [5. +0.j 2. +1.j]]


In [8]:
a = np.array([1,3,5,2], dtype=int)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (4,); int64
[1 3 5 2]


In [9]:
a = np.array([1,3,5,2], dtype=np.int64)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (4,); int64
[1 3 5 2]


In [10]:
a = np.array([1, 3, 5, 2], dtype=float)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (4,); float64
[1. 3. 5. 2.]


In [11]:
a = np.array([1, 3, 5, 2], dtype=np.float64)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (4,); float64
[1. 3. 5. 2.]


In [12]:
a = np.array([1, 3, 5, 2], dtype=np.double)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (4,); float64
[1. 3. 5. 2.]


In [13]:
a = np.array([(1, 3), [5, 2]], dtype=float)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

2; (2, 2); float64
[[1. 3.]
 [5. 2.]]


In [14]:
a = np.array([(1.2, 3), [5, 2]], dtype=int)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

2; (2, 2); int64
[[1 3]
 [5 2]]


## arange

In [15]:
a = np.arange(10)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (10,); int64
[0 1 2 3 4 5 6 7 8 9]


In [16]:
a = np.arange(0.0, 1.0, 0.1)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (10,); float64
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [17]:
a = np.arange(0.0, 1.0, 0.999_999_999)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (2,); float64
[0. 1.]


In [18]:
a = np.arange(0.0, 1.001, 0.1)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (11,); float64
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


## linspace

In [19]:
a = np.linspace(0.0, 1.0, 11)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (11,); float64
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [20]:
a = np.linspace(0, 9, 10)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (10,); float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [21]:
a = np.linspace(0, 9, 10, endpoint=False)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (10,); float64
[0.  0.9 1.8 2.7 3.6 4.5 5.4 6.3 7.2 8.1]


## fromiter

In [22]:
a = np.fromiter((i*i for i in range(5)), dtype=np.int64)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

1; (5,); int64
[ 0  1  4  9 16]


## And now let's see flags attribute.

In [23]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [24]:
a.flags.owndata

True

In [25]:
a = np.array([(1, 3), [5, 2]], dtype=float)
print(a.ndim, a.shape, a.dtype, sep='; ')
print(a)

2; (2, 2); float64
[[1. 3.]
 [5. 2.]]


In [26]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False