# Popular matrices and arrays creation

In [1]:
import numpy as np
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}', sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.0


In [2]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
np.zeros((3, 2), dtype=np.int64)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [4]:
np.zeros((2, 2), dtype=bool)

array([[False, False],
       [False, False]])

In [5]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.full((2, 3), 1.5)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [7]:
np.empty((2, 2), dtype=np.int32)

array([[0, 0],
       [0, 0]], dtype=int32)

In [8]:
np.empty((2, 2))

array([[0.00000000e+000, 1.16472806e-311],
       [1.16472806e-311, 1.16472806e-311]])

## Identity matrices

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.identity(2, dtype=np.int64)

array([[1, 0],
       [0, 1]])

In [11]:
np.identity(3, dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

## Additional samples of matrices creation

In [12]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(4, 3, -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(4, 3, 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a = np.array([[3*i+j+1 for j in range(3)] for i in range(3)], dtype=int)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
d = np.diag(a)
d

array([1, 5, 9])

In [18]:
d.flags   # owndata can be True or False, that depends on numpy version

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [19]:
a[1, 1] = 13

In [20]:
d

array([ 1, 13,  9])

In [21]:
a

array([[ 1,  2,  3],
       [ 4, 13,  6],
       [ 7,  8,  9]])

In [22]:
np.diagonal(a)

array([ 1, 13,  9])

In [23]:
np.diag([1, 2, 7])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 7]])

In [24]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [25]:
np.tril(a)

array([[ 1,  0,  0],
       [ 4, 13,  0],
       [ 7,  8,  9]])

In [26]:
np.triu(a)

array([[ 1,  2,  3],
       [ 0, 13,  6],
       [ 0,  0,  9]])

In [27]:
np.triu(a, k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [28]:
np.triu(a, k=-1)

array([[ 1,  2,  3],
       [ 4, 13,  6],
       [ 0,  8,  9]])