# Samples of reshaping

In [1]:
import numpy as np
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}', sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.0


In [2]:
a = np.arange(1, 13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
b = a.reshape(2, 6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [4]:
c = b.reshape(3, 4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
a.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
d = c.T
d

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [7]:
e = d.reshape(2, 6)
e

array([[ 1,  5,  9,  2,  6, 10],
       [ 3,  7, 11,  4,  8, 12]])

In [8]:
b.shape = (3, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
try:
    d.shape = (2, 6)
except BaseException as e:
    print(e)

Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.


In [10]:
b = b.reshape(2, -1)   # розмір останнього виміру буде обчислено автоматично
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
b.shape = (3, -1)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
e = b.flatten()
print('e:', e)

e: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
b.reshape(b.size)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
b.shape = (b.size,)

In [15]:
b.shape = (3, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
li = b.tolist()
print(li)
print(type(li[0][0]))

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
<class 'int'>


## Once more about transposition

In [17]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
b.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### Transposition of 3d-array

In [19]:
w = np.arange(24).reshape(2, 3, 4)
w

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
wT = w.T
wT

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [21]:
wT.shape

(4, 3, 2)

In [22]:
wT[0, 0, 0] = 13
w

array([[[13,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])