# Samples of indexing

In [1]:
import numpy as np
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}', sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.0


In [2]:
a = np.array([[1, 4], [7, 32]])
a

array([[ 1,  4],
       [ 7, 32]])

In [3]:
a[0]

array([1, 4])

In [4]:
a[1]

array([ 7, 32])

In [5]:
a[0][1]

np.int64(4)

In [6]:
a[0, 1]

np.int64(4)

In [7]:
type(a[0, 1])

numpy.int64

In [8]:
a.item(0, 1)

4

In [9]:
type(a.item(0, 1))

int

In [10]:
a.item(1)

4

In [11]:
type(a.item(1))

int

In [12]:
a[-1, -1]

np.int64(32)

In [13]:
a.item(-1, 0)

7

In [14]:
a.item(-1)

32

## linear index calculating

Let build matrix of size $3\times 4$.

In [15]:
a = np.array(range(12)).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Now, we let transpose our matrix. The result will be of size $4\times 3$.

In [17]:
b = a.T
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
b.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [19]:
b.item(2)

8

In [20]:
a.item(2)

2