# Samples of copying and assignment

In [1]:
import numpy as np
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}', sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.0


## Recollection lists copying

In [2]:
a_list = [[1, 2], [3, 4]]
a_list

[[1, 2], [3, 4]]

In [3]:
b_list = a_list
a_list is b_list

True

In [4]:
d_list = a_list.copy()
d_list[0][0] = 13
print(a_list)

[[13, 2], [3, 4]]


## ndarray copying and assignment

In [5]:
a = np.array([[1, 4], [7, 32]])
a

array([[ 1,  4],
       [ 7, 32]])

In [6]:
b = a
c = a.copy()
print(b is a)
print(c)

True
[[ 1  4]
 [ 7 32]]


In [7]:
b = a.T  # побудували транспоновану матрицю
b

array([[ 1,  7],
       [ 4, 32]])

In [8]:
c[0, 0] = -8
print('a:\n', a)
print('b:\n', b)
print('c:\n', c)

a:
 [[ 1  4]
 [ 7 32]]
b:
 [[ 1  7]
 [ 4 32]]
c:
 [[-8  4]
 [ 7 32]]


In [9]:
a[1] = [23, 34]
print('a:\n', a)
print('b:\n', b)
print('c:\n', c)

a:
 [[ 1  4]
 [23 34]]
b:
 [[ 1 23]
 [ 4 34]]
c:
 [[-8  4]
 [ 7 32]]


In [10]:
a[0] = 13   # broadcasting
print('a:\n', a)

a:
 [[13 13]
 [23 34]]


In [11]:
a.T[0] = 9
print('a:\n', a)

a:
 [[ 9 13]
 [ 9 34]]
