# Samples of element-wise operations, matrix multiplication and linear algebra

In [1]:
import numpy as np
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}', sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.0


In [2]:
a = np.arange(9, dtype=int).reshape(3,3)
v = np.arange(1, 4, dtype=int)
E3 = np.identity(3, dtype=int)
print('a =\n', a)
print('v =', v)
print('E3 =\n', E3)

a =
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
v = [1 2 3]
E3 =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3]:
2 * v

array([2, 4, 6])

In [4]:
2 * E3

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

In [5]:
a + E3

array([[1, 1, 2],
       [3, 5, 5],
       [6, 7, 9]])

In [6]:
v * v

array([1, 4, 9])

In [7]:
a * a

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [8]:
v @ v

np.int64(14)

In [9]:
a @ a

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [10]:
v @ a

array([24, 30, 36])

In [11]:
a @ v

array([ 8, 26, 44])

In [12]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

## Linear algebra

In [13]:
#!pip install scipy

In [14]:
import scipy.linalg as la

In [15]:
a = np.array([[1, 0, 0, 0], [1, 1, 0, 0], [1, 2, 1, 0], [1, 3, 3, 1]])
a

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 2, 1, 0],
       [1, 3, 3, 1]])

In [16]:
a1 = la.inv(a)
a1

array([[ 1., -0.,  0., -0.],
       [-1.,  1.,  0.,  0.],
       [ 1., -2.,  1.,  0.],
       [-1.,  3., -3.,  1.]])

In [17]:
a2 = np.array(a1, dtype=int)
a2

array([[ 1,  0,  0,  0],
       [-1,  1,  0,  0],
       [ 1, -2,  1,  0],
       [-1,  3, -3,  1]])

In [18]:
a2@a == np.identity(4)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Linear system ax=b solving

In [19]:
a = np.identity(3, dtype=int)
b = np.arange(1, 4)
np.hstack((a, b.reshape(3, 1)))  # only for the sake of nice printing

array([[1, 0, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 3]])

In [20]:
la.solve(a, b)

array([1., 2., 3.])