# Selecting and statistics

In [1]:
import numpy as np
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}', sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.0


## Slicing and indexing

In [2]:
a = np.arange(16, dtype=int).reshape(4, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
a[0]

array([0, 1, 2, 3])

In [4]:
a[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
a[0:2, :]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
a[:, 2:5]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [7]:
tmp = a[0:2, 1]
tmp

array([1, 5])

In [8]:
tmp[0] = 20
a

array([[ 0, 20,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
a[0:2, 1:2]

array([[20],
       [ 5]])

In [10]:
tmp = a[0:2, 1:3]
tmp

array([[20,  2],
       [ 5,  6]])

In [11]:
tmp[0, 0] = -5
a

array([[ 0, -5,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Samples of selecting

### Sample 1

In [12]:
a = np.arange(1, 17, dtype=int).reshape(4, -1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
a%3 == 0

array([[False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True],
       [False, False,  True, False]])

In [14]:
a[a%3 == 0]

array([ 3,  6,  9, 12, 15])

In [15]:
np.logical_and(a%3 == 0, a%5 == 1)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [16]:
(a%3 == 0) & (a%5 == 1)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
np.logical_or(a%3 == 0, a%5 == 1)

array([[ True, False,  True, False],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [False, False,  True,  True]])

In [18]:
(a%3 == 0) | (a%5 == 1)

array([[ True, False,  True, False],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [False, False,  True,  True]])

In [19]:
a[(a%3==0) & (a%5==1)]

array([6])

### Sample 2

Створимо матрицю, заповнену випадковими цілими числами від 0 до 100 включно.

Псевдовипадкові числа модулю <a href="https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random"
target=_blank 
rel="noopener noreferrer">numpy.random</a>
<br>
Документація на функцію <a href="https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng"
target=_blank 
rel="noopener noreferrer">default_rng</a>
<br>
Документація на метод <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers"
target=_blank 
rel="noopener noreferrer">Generator.integers</a>

In [20]:
rng = np.random.default_rng()
a = rng.integers(low=0, high=100, endpoint=True, dtype=np.int64, size=(8, 8))
a

array([[ 40,  33,   5,  77,  97,   8,  25,   7],
       [  1,  66,  35,  98,   6,   5,  64,  15],
       [ 77,  83,  19,  12,  93,  48,  33,  80],
       [ 82,  75,  93,  56,  75,   6,  82,  17],
       [ 16,  29,  16,  27,  43,  90,  92,  42],
       [ 12,  84,  41,   4,  92,  71,  50,  46],
       [ 83,  63,  28,  28,  62,  64,  32,   0],
       [ 87,  78, 100,  10,  38,   8,  36,  65]])

In [21]:
a < 90

array([[ True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False, False,  True],
       [ True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True]])

In [22]:
a % 3

array([[1, 0, 2, 2, 1, 2, 1, 1],
       [1, 0, 2, 2, 0, 2, 1, 0],
       [2, 2, 1, 0, 0, 0, 0, 2],
       [1, 0, 0, 2, 0, 0, 1, 2],
       [1, 2, 1, 0, 1, 0, 2, 0],
       [0, 0, 2, 1, 2, 2, 2, 1],
       [2, 0, 1, 1, 2, 1, 2, 0],
       [0, 0, 1, 1, 2, 2, 0, 2]])

In [23]:
a%3 == 0

array([[False,  True, False, False, False, False, False, False],
       [False,  True, False, False,  True, False, False,  True],
       [False, False, False,  True,  True,  True,  True, False],
       [False,  True,  True, False,  True,  True, False, False],
       [False, False, False,  True, False,  True, False,  True],
       [ True,  True, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False,  True],
       [ True,  True, False, False, False, False,  True, False]])

In [24]:
np.logical_and(a < 90, a%3 == 0)

array([[False,  True, False, False, False, False, False, False],
       [False,  True, False, False,  True, False, False,  True],
       [False, False, False,  True, False,  True,  True, False],
       [False,  True, False, False,  True,  True, False, False],
       [False, False, False,  True, False, False, False,  True],
       [ True,  True, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False,  True],
       [ True,  True, False, False, False, False,  True, False]])

In [25]:
(a < 90) & (a%3 == 0)

array([[False,  True, False, False, False, False, False, False],
       [False,  True, False, False,  True, False, False,  True],
       [False, False, False,  True, False,  True,  True, False],
       [False,  True, False, False,  True,  True, False, False],
       [False, False, False,  True, False, False, False,  True],
       [ True,  True, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False,  True],
       [ True,  True, False, False, False, False,  True, False]])

In [26]:
a[np.logical_and(a < 90, a%3 == 0)]

array([33, 66,  6, 15, 12, 48, 33, 75, 75,  6, 27, 42, 12, 84, 63,  0, 87,
       78, 36])

## Samples of statistics

In [27]:
a = np.arange(16, dtype=int).reshape(4, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
a.sum()

np.int64(120)

In [29]:
a.sum(axis=0)

array([24, 28, 32, 36])

In [30]:
a.sum(axis=1)

array([ 6, 22, 38, 54])

In [31]:
np.sum(a, axis=1)

array([ 6, 22, 38, 54])

In [32]:
np.median(a)

np.float64(7.5)

In [33]:
np.average(a)

np.float64(7.5)

In [34]:
np.average(a, weights=np.arange(1, 17).reshape(a.shape))

np.float64(10.0)

In [35]:
b = a*a
b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [36]:
np.median(b)

np.float64(56.5)

In [37]:
(64+49)/2

56.5