# Additional samples

In [1]:
import numpy as np
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}', sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.0


## Broadcasting

In [2]:
v = np.arange(1, 4, dtype=int)
v_1_3 = v.reshape(1, 3) 
v_3_1 = v.reshape(3, 1) 
print('v =', v)
print('v_1_3 =', v_1_3)
print('v_3_1 =\n', v_3_1)

v = [1 2 3]
v_1_3 = [[1 2 3]]
v_3_1 =
 [[1]
 [2]
 [3]]


In [3]:
ones3 = np.ones((3, 3), dtype=int)
print('ones3 =\n', ones3)

ones3 =
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
ones3 * v_1_3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [5]:
ones3 * v_3_1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [6]:
ones3 * v

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
v_1_3 + v_3_1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

## Indexing by sequence 

In [8]:
a = np.arange(16, dtype=int).reshape(4, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
a[[1, 2], [0, 3]]

array([ 4, 11])

In [10]:
a[(1, 2), (0, 3)]

array([ 4, 11])

In [11]:
a[[0, 3]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [12]:
tmp = a[[0, 3]][:, [0, 2]]
tmp

array([[ 0,  2],
       [12, 14]])

In [13]:
tmp = a[:, [0, 2]]
tmp

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [14]:
tmp[0, 0] = 13
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Increasing dimensions 

In [15]:
x = np.array([1, 2, 3, 6])
x

array([1, 2, 3, 6])

In [16]:
x[np.newaxis, :]

array([[1, 2, 3, 6]])

In [17]:
x[:, np.newaxis]

array([[1],
       [2],
       [3],
       [6]])

## Joining and splitting

In [18]:
x = np.arange(3)
a = np.arange(1, 10).reshape(3, -1)
print('x =', x)
print('a =\n', a)

x = [0 1 2]
a =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
np.concatenate((x, x))

array([0, 1, 2, 0, 1, 2])

In [20]:
np.hstack((x, x))

array([0, 1, 2, 0, 1, 2])

In [21]:
print(x[np.newaxis, :])
np.hstack((x[np.newaxis, :], x[np.newaxis, :]))

[[0 1 2]]


array([[0, 1, 2, 0, 1, 2]])

In [22]:
np.concatenate((x[np.newaxis, :], x[np.newaxis, :]), 1)

array([[0, 1, 2, 0, 1, 2]])

In [23]:
np.vstack((x, x))

array([[0, 1, 2],
       [0, 1, 2]])

In [24]:
np.vstack((x[np.newaxis, :], x[np.newaxis, :]))

array([[0, 1, 2],
       [0, 1, 2]])

In [25]:
np.concatenate((x[np.newaxis, :], x[np.newaxis, :]), 0)

array([[0, 1, 2],
       [0, 1, 2]])

In [26]:
b = np.concatenate((np.tril(a), np.triu(a)), 1)
b

array([[1, 0, 0, 1, 2, 3],
       [4, 5, 0, 0, 5, 6],
       [7, 8, 9, 0, 0, 9]])

In [27]:
tmp = np.hsplit(b, (3,))
print(*tmp, sep='\n\n')

[[1 0 0]
 [4 5 0]
 [7 8 9]]

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [28]:
tmp = np.hsplit(b, (2, 5))
print(*tmp, sep='\n\n')

[[1 0]
 [4 5]
 [7 8]]

[[0 1 2]
 [0 0 5]
 [9 0 0]]

[[3]
 [6]
 [9]]


In [29]:
tmp = np.hsplit(b, 3)
print(*tmp, sep='\n\n')

[[1 0]
 [4 5]
 [7 8]]

[[0 1]
 [0 0]
 [9 0]]

[[2 3]
 [5 6]
 [0 9]]


In [30]:
tmp = np.vsplit(b, (1,))
print(*tmp, sep='\n\n')

[[1 0 0 1 2 3]]

[[4 5 0 0 5 6]
 [7 8 9 0 0 9]]
