# pandas.Series

In [25]:
import numpy as np
import pandas as pd
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}',  f'pandas version {pd.__version__}',sep='\n')

linux
3.14.2 (main, Jan 24 2026, 16:11:19) [GCC 15.2.0]
numpy version 2.4.1
pandas version 3.0.0


In [26]:
from pathlib import Path

### Створюємо об'єкт <code>Series</code> з індексом за умовчанням

In [27]:
obj = pd.Series([1, 8, -3, 4])
obj

0    1
1    8
2   -3
3    4
dtype: int64

In [4]:
obj.dtype

dtype('int64')

In [28]:
obj.size

4

In [29]:
len(obj)

4

<b> Дані </b>

Якщо можливо, то значенням атрибуту <code>values</code> буде <code>np.ndarray</code>

In [30]:
obj.values

array([ 1,  8, -3,  4])

Рекомендований спосіб конвертації на <code>np.ndarray</code>:

In [31]:
obj.to_numpy()

array([ 1,  8, -3,  4])

і, якщо треба гарантовано отримати дані без утворення копій та перетворень, то так

In [9]:
obj.array

<NumpyExtensionArray>
[1, 8, -3, 4]
Length: 4, dtype: int64

<i>Примітка</i>. У <code>pandas 2.0</code> тип був <code>PandasArray</code>. Насправді це внутрішній тип, який використовується переважно засобами бібліотеки.

<b> Індекс </b>

Типів індексів є кілька. За умовчанням створюється такий індекс.

In [32]:
obj.index

RangeIndex(start=0, stop=4, step=1)

### Створюємо об'єкт <code>Series</code> з власними мітками даних

In [33]:
obj2 = pd.Series({'MA':101, 'ALG':99, 'DM':85}, dtype=int, name="ім'я послідовності даних")
obj2

MA     101
ALG     99
DM      85
Name: ім'я послідовності даних, dtype: int64

In [34]:
obj2.dtypes

dtype('int64')

In [35]:
obj2 = pd.Series([101, 99, 85], index=('MA', 'ALG', 'DM'))
obj2

MA     101
ALG     99
DM      85
dtype: int64

In [36]:
obj2.size

3

In [37]:
obj2.index

Index(['MA', 'ALG', 'DM'], dtype='str')

In [38]:
obj2a = pd.Series([101, 99, 85], index=obj2.index)
obj2a

MA     101
ALG     99
DM      85
dtype: int64

In [39]:
import csv

def load_data(fname, skip_headers=True):
    data = list()
    with open(fname, newline='', encoding='utf-8') as f:
        r = csv.reader(f)
        if skip_headers:
            next(r)
        for row in r:
            if row:
                data.append(row)
    return data

Файл <code>population.csv</code> містить чисельність населення деяких міст України станом на 2014 рік (за даними Wikipedia).

In [40]:
tmp = load_data(Path('prepare', 'population.csv'))
tmp[:5]

[['Київ ', '2869'],
 ['Харків ', '1451'],
 ['Одеса ', '1017'],
 ['Дніпро', '993'],
 ['Донецьк ', '950']]

In [14]:
raw_data = {el[0].strip():int(el[1]) for el in tmp[:5]}
raw_data

{'Київ': 2869, 'Харків': 1451, 'Одеса': 1017, 'Дніпро': 993, 'Донецьк': 950}

In [15]:
population = pd.Series(raw_data)
population

Київ       2869
Харків     1451
Одеса      1017
Дніпро      993
Донецьк     950
dtype: int64

In [16]:
population = pd.Series(data=(int(el[1]) for el in tmp), index=(el[0].strip() for el in tmp))
population.head()

Київ       2869
Харків     1451
Одеса      1017
Дніпро      993
Донецьк     950
dtype: int64

In [17]:
population.tail()

Бровари           99
Євпаторія        107
Алчевськ         110
Павлоград        110
Сєвєродонецьк    109
dtype: int64

In [18]:
population.head(3)

Київ      2869
Харків    1451
Одеса     1017
dtype: int64

In [24]:
population.array

<NumpyExtensionArray>
[2869, 1451, 1017,  993,  950,  766,  729,  652,  495,  459,  345,  424,  372,
  338,  352,  298,  296,  296,  285,  266,  262,  271,  269,  250,  254,  227,
  241,  233,  217,  226,  216,  211,  163,  157,  145,  116,  116,  118,  117,
   99,  107,  110,  110,  109]
Length: 44, dtype: int64

In [25]:
population.index

Index(['Київ', 'Харків', 'Одеса', 'Дніпро', 'Донецьк', 'Запоріжжя', 'Львів',
       'Кривий Ріг', 'Миколаїв', 'Маріуполь', 'Севастополь', 'Луганськ',
       'Вінниця', 'Сімферополь', 'Макіївка', 'Херсон', 'Чернігів', 'Полтава',
       'Черкаси', 'Хмельницький', 'Чернівці', 'Житомир', 'Суми', 'Рівне',
       'Горлівка', 'Івано-Франківськ', 'Кам'янське', 'Кропивницький',
       'Тернопіль', 'Кременчук', 'Луцьк', 'Біла Церква', 'Краматорськ',
       'Мелітополь', 'Керч', 'Ужгород', 'Бердянськ', 'Нікополь', 'Слов'янськ',
       'Бровари', 'Євпаторія', 'Алчевськ', 'Павлоград', 'Сєвєродонецьк'],
      dtype='str')

In [19]:
population.name = 'population'
population.index.name = 'city'
population.head()

city
Київ       2869
Харків     1451
Одеса      1017
Дніпро      993
Донецьк     950
Name: population, dtype: int64

### Індексація та зрізи

<code>at</code>,<code>loc</code> використовують індекси (мітки даних)<br>
<code>iat</code>,<code>iloc</code> використовують номери

In [27]:
population.at['Київ'], population.loc['Київ']

(np.int64(2869), np.int64(2869))

In [28]:
population.iat[0], population.iloc[0]

(np.int64(2869), np.int64(2869))

<code>...at</code> надають доступ до одного елемента даних<br>
<code>...loc</code> надають доступ до певної частини даних (але може складатись з одного елемента)

Зрізи можуть бути по індексах та по номерах.<br>
Зрізи по номерах не включають праву межу, [from, to).<br>
Зрізи по індексах <b>включають</b> праву межу, [from, to].<br>

In [29]:
population.iloc[0:3]

city
Київ      2869
Харків    1451
Одеса     1017
Name: population, dtype: int64

In [30]:
population.loc['Київ':'Дніпро']

city
Київ      2869
Харків    1451
Одеса     1017
Дніпро     993
Name: population, dtype: int64

In [31]:
population.loc[['Київ', 'Дніпро']]

city
Київ      2869
Дніпро     993
Name: population, dtype: int64

In [32]:
population.iloc[[1, 2, 7]]

city
Харків        1451
Одеса         1017
Кривий Ріг     652
Name: population, dtype: int64

<b>Індексація</b> [] можлива по індексу (по номерах планують прибрати), зрізи можливі по індексах та по номерах.

In [33]:
population['Київ']

np.int64(2869)

In [34]:
population[0:3]

city
Київ      2869
Харків    1451
Одеса     1017
Name: population, dtype: int64

In [35]:
population['Київ':'Дніпро']

city
Київ      2869
Харків    1451
Одеса     1017
Дніпро     993
Name: population, dtype: int64

### Векторні операції, фільтри та вибірки

Переведемо чисельність населення з тисяч у мільйони. (Результат - новий об'єкт Series.)

In [36]:
population/1000

city
Київ                2.869
Харків              1.451
Одеса               1.017
Дніпро              0.993
Донецьк             0.950
Запоріжжя           0.766
Львів               0.729
Кривий Ріг          0.652
Миколаїв            0.495
Маріуполь           0.459
Севастополь         0.345
Луганськ            0.424
Вінниця             0.372
Сімферополь         0.338
Макіївка            0.352
Херсон              0.298
Чернігів            0.296
Полтава             0.296
Черкаси             0.285
Хмельницький        0.266
Чернівці            0.262
Житомир             0.271
Суми                0.269
Рівне               0.250
Горлівка            0.254
Івано-Франківськ    0.227
Кам'янське          0.241
Кропивницький       0.233
Тернопіль           0.217
Кременчук           0.226
Луцьк               0.216
Біла Церква         0.211
Краматорськ         0.163
Мелітополь          0.157
Керч                0.145
Ужгород             0.116
Бердянськ           0.116
Нікополь            0.118
Слов'ян

<b>Обчислення умови</b>. Для кожного міста визначимо, чи правда, що кількість його мешканців більша за 900.

In [37]:
population > 900

city
Київ                 True
Харків               True
Одеса                True
Дніпро               True
Донецьк              True
Запоріжжя           False
Львів               False
Кривий Ріг          False
Миколаїв            False
Маріуполь           False
Севастополь         False
Луганськ            False
Вінниця             False
Сімферополь         False
Макіївка            False
Херсон              False
Чернігів            False
Полтава             False
Черкаси             False
Хмельницький        False
Чернівці            False
Житомир             False
Суми                False
Рівне               False
Горлівка            False
Івано-Франківськ    False
Кам'янське          False
Кропивницький       False
Тернопіль           False
Кременчук           False
Луцьк               False
Біла Церква         False
Краматорськ         False
Мелітополь          False
Керч                False
Ужгород             False
Бердянськ           False
Нікополь            False
Слов'ян

Виберемо ті міста, що відповідають умові.

In [38]:
population[population > 900]

city
Київ       2869
Харків     1451
Одеса      1017
Дніпро      993
Донецьк     950
Name: population, dtype: int64

### Оброблення відсутніх даних

Файл <code>area.csv</code> містить площу деяких міст України (за даними з інтернету). Але дані заповнені не для всіх міст, що наявні в таблиці. Замість відсутніх значень під час завантаження підставляється <code>np.nan</code> (not a number, виділене значення дійсного числового типу з плаваючою крапкою).

In [20]:
tmp = load_data(Path('prepare', 'area.csv'))
area = pd.Series((float(el[1]) if el[1] and not el[1].isspace() else np.nan for el in tmp), 
                 index=(el[0].strip() for el in tmp))
area.head(5)

Херсон       NaN
Чернігів     NaN
Київ        83.6
Харків      35.0
Одеса       16.2
dtype: float64

Використаємо розширений тип.

In [41]:
tmp = load_data(Path('prepare', 'area.csv'))
area = pd.Series((float(el[1]) if el[1] and not el[1].isspace() else np.nan for el in tmp), 
                 index=(el[0].strip() for el in tmp), dtype='Float64')
area.head(5)

Херсон      <NA>
Чернігів    <NA>
Київ        83.6
Харків      35.0
Одеса       16.2
dtype: Float64

Якщо відсутнє значення дійсного типу може бути зображене дійсним "нечислом", то у випадку цілих типів, наявність спеціального значення для позначення відсутності значення є важливою.

In [43]:
tmp = load_data(Path('prepare', 'area.csv'))
area_int = pd.Series((int(float(el[1])) if el[1] and not el[1].isspace() else None for el in tmp), 
                 index=(el[0].strip() for el in tmp), dtype='Int64')
area_int.head(5)

Херсон      <NA>
Чернігів    <NA>
Київ          83
Харків        35
Одеса         16
dtype: Int64

Перевіримо на відсутність значень. 

In [44]:
area.isna()

Херсон               True
Чернігів             True
Київ                False
Харків              False
Одеса               False
Дніпро1             False
Донецьк             False
Запоріжжя           False
Львів               False
Кривий Ріг          False
Миколаїв            False
Полтава             False
Черкаси              True
Хмельницький        False
Чернівці            False
Житомир              True
Суми                False
Рівне                True
Горлівка            False
Івано-Франківськ     True
Кам'янське          False
Кропивницький       False
Тернопіль            True
Кременчук           False
Луцьк                True
Біла Церква          True
Краматорськ          True
Мелітополь           True
Керч                 True
Ужгород              True
Бердянськ            True
Нікополь             True
Маріуполь           False
Севастополь         False
Луганськ            False
Вінниця              True
Сімферополь         False
Макіївка            False
Слов'янськ  

Відсутні значення можна вилучити з послідовності (dropna) або можна заповнити (fillna).

In [45]:
area.dropna(inplace=True)
area

Київ             83.6
Харків           35.0
Одеса            16.2
Дніпро1          40.5
Донецьк          57.1
Запоріжжя        27.8
Львів            17.1
Кривий Ріг       43.1
Миколаїв         26.0
Полтава          10.4
Хмельницький      9.3
Чернівці         15.2
Суми             14.7
Горлівка         42.2
Кам'янське       13.8
Кропивницький    10.3
Кременчук         9.6
Маріуполь        24.9
Севастополь      86.3
Луганськ         28.6
Сімферополь      42.6
Макіївка         42.5
dtype: Float64

### Векторні операції над послідовностями з різними індексами

Знайдемо щільність населення міст.

При обчисленні векторних операцій над різними послідовностями виконується з'єднання (outer join) за індексами: новий індекс утворюється як об'єднання індексів.

In [44]:
res = population/area
res

city
Євпаторія                <NA>
Івано-Франківськ         <NA>
Алчевськ                 <NA>
Бердянськ                <NA>
Бровари                  <NA>
Біла Церква              <NA>
Вінниця                  <NA>
Горлівка             6.018957
Дніпро                   <NA>
Дніпро1                  <NA>
Донецьк             16.637478
Житомир                  <NA>
Запоріжжя           27.553957
Кам'янське          17.463768
Керч                     <NA>
Київ                34.318182
Краматорськ              <NA>
Кременчук           23.541667
Кривий Ріг           15.12761
Кропивницький       22.621359
Луганськ            14.825175
Луцьк                    <NA>
Львів               42.631579
Макіївка             8.282353
Маріуполь           18.433735
Мелітополь               <NA>
Миколаїв            19.038462
Нікополь                 <NA>
Одеса               62.777778
Павлоград                <NA>
Полтава             28.461538
Рівне                    <NA>
Севастополь          3.997683
Слов'

In [45]:
res.dropna()

city
Горлівка          6.018957
Донецьк          16.637478
Запоріжжя        27.553957
Кам'янське       17.463768
Київ             34.318182
Кременчук        23.541667
Кривий Ріг        15.12761
Кропивницький    22.621359
Луганськ         14.825175
Львів            42.631579
Макіївка          8.282353
Маріуполь        18.433735
Миколаїв         19.038462
Одеса            62.777778
Полтава          28.461538
Севастополь       3.997683
Суми              18.29932
Сімферополь       7.934272
Харків           41.457143
Хмельницький     28.602151
Чернівці         17.236842
dtype: Float64

До об'єктів <b>Series</b> застосовні статистики, що застосовні до багатовимірних масивів <b>numpy.ndarray</b>.

Найбільша щільність населення за наявними даними складає

In [46]:
res.max()

np.float64(62.77777777777778)

Середня щільність населення за наявними даними складає

In [47]:
res.mean()

np.float64(22.631476561168956)

In [48]:
res.count()

np.int64(21)

In [49]:
res.size

45

### Унікальність значень

Мітки даних унікальними можуть не бути, але таке не часто буває потрібно.

In [50]:
obj2 = pd.Series((101, 99, 85), index=('MA', 'MA', 'DM'), dtype=int, name="ім'я послідовності даних")
obj2

MA    101
MA     99
DM     85
Name: ім'я послідовності даних, dtype: int64

In [51]:
obj2['MA']

MA    101
MA     99
Name: ім'я послідовності даних, dtype: int64

Значення можуть повторюватись.

In [52]:
obj2 = pd.Series({'MA':99, 'ALG':99, 'DM':85}, dtype=int, name="ім'я послідовності даних")
obj2

MA     99
ALG    99
DM     85
Name: ім'я послідовності даних, dtype: int64

In [53]:
obj2.is_unique

False

In [54]:
obj2.unique()

array([99, 85])

In [55]:
obj2.nunique()

2